Document: nwsmtp
Title: Debian nwsmtp Manual
Author: <insert document author here>
Abstract: This manual describes what nwsmtp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nwsmtp/nwsmtp.sgml.gz

Format: postscript
Files: /usr/share/doc/nwsmtp/nwsmtp.ps.gz

Format: text
Files: /usr/share/doc/nwsmtp/nwsmtp.text.gz

Format: HTML
Index: /usr/share/doc/nwsmtp/html/index.html
Files: /usr/share/doc/nwsmtp/html/*.html
